### ISSUE TITLE
Build fails: file not found for module `procedures`

### ISSUE THREAD

**Issue by NateChoe1** [scratchnative/scratchnative#2]
Building this program with Cargo fails with the error "file not found for module \`procedures\`"

    $ cargo build
       Compiling scratchnative v0.1.0 (/home/nate/repos/scratchnative)
    error[E0583]: file not found for module `procedures`
      --> src/parser/ast/mod.rs:11:1
       |
    11 | mod procedures;
       | ^^^^^^^^^^^^^^^
       |
       = help: to create the module `procedures`, create file "src/parser/ast/procedures.rs" or "src/parser/ast/procedures/mod.rs"
    
    error[E0425]: cannot find function `procedures_to_statement` in module `procedures`
       --> src/parser/ast/mod.rs:254:37
        |
    254 |         "procedures" => procedures::procedures_to_statement(file, block.clone(), str_array[1]),
        |                                     ^^^^^^^^^^^^^^^^^^^^^^^ not found in `procedures`
    
    Some errors have detailed explanations: E0425, E0583.
    For more information about an error, try `rustc --explain E0425`.
    error: could not compile `scratchnative` due to 2 previous errors

Output of `cargo -V`

    $ cargo -V
    cargo 1.66.1

**Comment by rdmsr** [comment]
I forgot to push a file. I fixed this locally and will eventually commit it

**Comment by SeizureSaladd** [comment]
hey i'm still getting the same error. have you pushed the file yet?
